<a href="https://colab.research.google.com/github/MuhammadTayyab8/Artificial-Intelligence-using-Python---DigiSkills/blob/main/Artificial_Intelligence_using_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Intelligence using Python

**Week # 1**

In [ ]:
# ============================================
# PYTHON WEEK 1 PRACTICE NOTEBOOK
# ============================================

print("Welcome to Python Practice Week 1")
print("----------------------------------")

Welcome to Python Practice Week 1
----------------------------------

In [ ]:
# ============================================
# 1. VARIABLES
# ============================================

name = "Tayyab"
age = 20
is_student = True

print("\nVARIABLES")
print(name)
print(age)
print(is_student)

VARIABLES
Tayyab
20
True

In [ ]:
# ============================================
# 2. DATA TYPES
# ============================================

print("\nDATA TYPES")

print(type(name))
print(type(age))
print(type(is_student))

DATA TYPES
<class 'str'>
<class 'int'>
<class 'bool'>

In [ ]:
# ============================================
# 3. LISTS
# ============================================

print("LISTS")

fruits = ["apple", "banana", "mango"]

print(fruits)
print(fruits[0])

fruits.append("orange")

print(fruits)

LISTS
['apple', 'banana', 'mango']
apple
['apple', 'banana', 'mango', 'orange']

In [ ]:
# ============================================
# 4. TUPLES
# ============================================

print("TUPLES")

coordinates = (10, 20)

print(coordinates)

TUPLES
(10, 20)

In [ ]:
# ============================================
# 5. SETS
# ============================================

print("SETS")

numbers = {1, 2, 3, 3, 4}

print(numbers)

SETS
{1, 2, 3, 4}

In [ ]:
# ============================================
# 6. DICTIONARIES
# ============================================

print("DICTIONARIES")

student = {
    "name": "Ali",
    "age": 22,
    "grade": "A"
}

print(student)
print(student["name"])

DICTIONARIES
{'name': 'Ali', 'age': 22, 'grade': 'A'}
Ali

In [ ]:
# ============================================
# 7. TYPE CONVERSION
# ============================================

print("TYPE CONVERSION")

num = "100"
print(type(num))
converted_num = int(num)

print(converted_num)
print(type(converted_num))

TYPE CONVERSION
<class 'str'>
100
<class 'int'>

In [ ]:
# ============================================
# 8. OPERATORS
# ============================================

print("OPERATORS")

a = 10
b = 3

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a > b)

OPERATORS
13
7
30
3.3333333333333335
True

In [ ]:
# ============================================
# 9. CONDITIONAL STATEMENTS
# ============================================

print("IF ELSE")

marks = 75

if marks >= 80:
    print("Grade A")
elif marks >= 60:
    print("Grade B")
else:
    print("Grade C")

IF ELSE
Grade B

In [ ]:

# ============================================
# 10. FOR LOOP
# ============================================

print("FOR LOOP")

for i in range(5):
    print(i)

FOR LOOP
0
1
2
3
4

In [ ]:
# ============================================
# 11. WHILE LOOP
# ============================================

print("WHILE LOOP")

count = 1

while count <= 5:
    print(count)
    count += 1

WHILE LOOP
1
2
3
4
5

In [ ]:
# ============================================
# 12. NESTED LOOP
# ============================================

print("NESTED LOOP")

for i in range(3):
    for j in range(2):
        print(i, j)

n = 5
for i in range(1, n + 1):
    print(" " * (n - i) + "*" * (2 * i - 1))

NESTED LOOP
0 0
0 1
1 0
1 1
2 0
2 1
    *
   ***
  *****
 *******
*********

In [ ]:
# ============================================
# 13. LOOP THROUGH STRING
# ============================================

print("\nSTRING LOOP")

word = "Python"

for letter in word:
    print(letter)

STRING LOOP
P
y
t
h
o
n
P
y
t
h
o
n

In [ ]:
# ============================================
# 14. LOOP THROUGH DICTIONARY
# ============================================

print("\nDICTIONARY LOOP")

for key, value in student.items():
    print(key, value)

DICTIONARY LOOP
name Ali
age 22
grade A

In [ ]:
# ============================================
# 15. FUNCTIONS
# ============================================

print("\nFUNCTIONS")

def greet():
    print("Hello World")

greet()

FUNCTIONS
Hello World

In [ ]:
# ============================================
# 16. FUNCTION PARAMETERS
# ============================================

print("\nFUNCTION PARAMETERS")

def add_numbers(x, y):
    return x + y

result = add_numbers(5, 7)

print(result)

FUNCTION PARAMETERS
12

In [ ]:
# ============================================
# 17. VARIABLE SCOPE
# ============================================

print("\nVARIABLE SCOPE")

global_var = "I am global"

def test_scope():
    local_var = "I am local"
    print(local_var)
    print(global_var)

test_scope()

VARIABLE SCOPE
I am local
I am global

In [ ]:
# ============================================
# 18. LAMBDA FUNCTIONS
# ============================================

print("\nLAMBDA FUNCTION")

square = lambda x: x * x

print(square(5))


print("\nPractice notebook week1 completed!")

LAMBDA FUNCTION
25

Practice notebook week1 completed!

> Assignments of week#1

In [ ]:
# Assignment 1 — Student Bio
# Create variables:
# your name
# age
# favorite AI field
# Print them.

student_name = "Muhammad Tayyab"
student_age = 18
student_ai_field = "Artificial Intelligence"

print("Student Name: " + student_name)
print("Student Age: " + str(student_age))
print("Student AI Field: " + student_ai_field)


# Assignment 2 — Calculator
# Take 2 numbers:
# add
# subtract
# multiply
# divide
# Print all results.
def calculator(num1, num2):
  print(num1 + num2)
  print(num1 - num2)
  print(num1 * num2)
  print(num1 / num2)

calculator(int(input("Enter first number: ")), int(input("Enter second number: ")))


# Assignment 3 — Even/Odd Checker
# Check:
# if number even → print EVEN
# else → print ODD

num = 10
if num%2 == 0:
  print("EVEN")
else:
  print("ODD")


# Assignment 4 — Multiplication Table
# Print table of 7 using loop.

for i in (range(1, 11)):
  print(f"7 X {i} = {7*i}")

# Assignment 5 — List Practice
# Create list of 5 AI technologies.
# Then:
# print first item
# add one more item
# remove one item

ai_technology = ["Machine Learning", "Deep Learning", "NLP", "Computer Vision", "Reinforcement Learning"]
print(ai_technology[0])
ai_technology.append("Generative AI")
print(ai_technology)
ai_technology.remove("Computer Vision")
print(ai_technology)


# Assignment 6 — Dictionary Practice
# Create dictionary:
# student = {
#    "name": "",
#    "course": "",
#    "week": ""
# }
# Loop through it and print keys + values.

student_dictionary = {
    "name": "Muhammad Tayyab",
    "course": "Artificial Intelligence",
    "week": "1"
}

for key, value in student_dictionary.items():
  print(f"{key}: {value}")


# Assignment 7 — Function
# Create function:
# def square(number):
# Return square of number.
def square(num):
  return num*num
square(4)


# Assignment 8 — Mini Challenge ⭐
# Create simple login system:
# correct_username = "admin"
# correct_password = "1234"
# If correct:
# Login Successful
# Else:
# Access Denied

correct_username = "admin"
correct_password = "1234"
user_name = input("Enter username: ")
user_password = input("Enter password: ")

if user_name == correct_username and user_password == correct_password:
  print("Login Successful")
else:
  print("Access Denied")

Student Name: Muhammad Tayyab
Student Age: 18
Student AI Field: Artificial Intelligence
Enter first number: 6
Enter second number: 3
9
3
18
2.0
EVEN
7 X 1 = 7
7 X 2 = 14
7 X 3 = 21
7 X 4 = 28
7 X 5 = 35
7 X 6 = 42
7 X 7 = 49
7 X 8 = 56
7 X 9 = 63
7 X 10 = 70
Machine Learning
['Machine Learning', 'Deep Learning', 'NLP', 'Computer Vision', 'Reinforcement Learning', 'Generative AI']
['Machine Learning', 'Deep Learning', 'NLP', 'Reinforcement Learning', 'Generative AI']

**Week # 2**

In [ ]:
# MODULES

import math

print(math.sqrt(25))
print(math.pi)
print(math.factorial(5))


import random

print(random.randint(1, 10))
fruits = ["mango", "apple", "banana", "graphs"]
print(random.choice(fruits))

5.0
3.141592653589793
120
1
banana

In [ ]:
# OOP

# CLASS + OBJECT
class Student:
  def say_hello(self):
    print("Hello Student!")

student1 = Student()
student1.say_hello()

print("\n------------")

# Constructor (init) and Instance Methods
class Student:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def bio(self):
    print(f"Name: {self.name}, Age: {self.age}")


student1 = Student("Muhammad Tayyab", 18)
print(student1.name)
print(student1.age)
student1.bio()

print("\n------------")

# Encapsulation (Public/Private)
class BankAccount:
  def __init__(self):
    self.__balance = 1000

account = BankAccount()
# This will give error
# print(account.__balance)

print("\n------------")

# Getters & Setters
class BankAccount:
  def __init__(self):
    self.__balance = 1000

  def get_balance(self):
    return self.__balance

  def set_balance(self, new_balance):
    self.__balance = new_balance

account = BankAccount()
print(account.get_balance())
account.set_balance(1500)
print(account.get_balance())

print("\n------------")

# Inheritance
class Animal:
    def speak(self):
        print("Animal speaks")

class Dog(Animal):
    def bark(self):
        print("Dog barks")

dog1 = Dog()

dog1.speak()
dog1.bark()

print("\n------------")

# METHOD OVERRIDING
class Animal:
    def speak(self):
        print("Animal speaks")

class Dog(Animal):
    def speak(self):
        print("Dog barks")

dog1 = Dog()

dog1.speak()

print("\n------------")

# POLYMORPH
class Bird:

    def sound(self):
        print("Bird sound")


class Parrot(Bird):

    def sound(self):
        print("Parrot talking")


class Crow(Bird):

    def sound(self):
        print("Crow cawing")


birds = [Parrot(), Crow()]

for bird in birds:
    bird.sound()


# SPECIAL METHODS
class Book:

    def __init__(self, title):
        self.title = title

    def __str__(self):
        return f"Book: {self.title}"


book1 = Book("Python Basics")

print(book1)

Hello Student!

------------
Muhammad Tayyab
18
Name: Muhammad Tayyab, Age: 18

------------

------------
1000
1500

------------
Animal speaks
Dog barks

------------
Dog barks

------------
Parrot talking
Crow cawing
<__main__.Book object at 0x7d9146327ce0>

In [ ]:
# FILE HANDLING

# -- write
file = open("text.txt", "w")
file.write("Hello Tayyab!")
file.close()

# -- read
file = open("text.txt", "r")
content = file.read()
print(content)
file.close()

print("\n--------------")

# -- append
file = open("text.txt", "a")
file.write("\nWrite new line")
file.close()

# -- read with "with"
with open("text.txt", "r") as file:
  content = file.read()
  print(content)

Hello Tayyab!

--------------
Hello Tayyab!
Write new line

In [ ]:
# EXCEPTIONS

try:
    number = int(input("Enter number: "))
    print(number)

except:
    print("Invalid input")

print("\n--------------")


try:
  num1 = int(input("Enter num1: "))
  num2 = int(input("Enter num2: "))

  result = num1/num2

except ZeroDivisionError:
  print("Cannot divide by zero")

except ValueError:
  print("Invalid input")

else:
  print(result)

finally:
  print("Program finished")

print("\n-----------")

# raise custom expection
class InvalidAgeError(Exception):
    pass

age = -1

if age < 0:
    raise InvalidAgeError("Invalid age entered")

Enter number: 80
80

--------------
Enter num1: 80
Enter num2: 10
8.0
Program finished

-----------

InvalidAgeError: Invalid age entered

Assignments of Week#2

In [ ]:
# Assignment 1 — Calculator Class
# Create class:
# Calculator
# Methods:
# add
# subtract
# multiply
# divide

class Calculator:
  def __init__(self, num1, num2):
    self.num1 = num1
    self.num2 = num2

  def add(self):
    print(self.num1 + self.num2)

  def subtract(self):
    print(self.num1 - self.num2)

  def multiply(self):
    print(self.num1 * self.num2)

  def divide(self):
    print(self.num1 / self.num2)

calculator = Calculator(10, 5)
calculator.add()
calculator.subtract()
calculator.multiply()
calculator.divide()


# Assignment 2 — Student Class
# Attributes:
# name
# age
# course
# Method:
# display_info()

print("\n=============")

class Student:
  def __init__(self, name, age, course):
    self.name = name
    self.age = age
    self.course = course

  def display_info(self):
    print(f"Name: {self.name}, Age: {self.age}, Course: {self.course}")

student = Student("Muhammad Tayyab", 18, "Artificial Intelligence")
student.display_info()

print("\n=============")


# Assignment 6 ⭐ MINI PROJECT
# Create simple:
# Bank Account System
# Features:
# deposit
# withdraw
# show balance

class Bank:
  def __init__(self):
    self.__balance = 0

  def deposit(self, amount):
    self.__balance += amount
    print(f"Deposit: {amount}")

  def withdraw(self, amount):
    if amount > self.__balance:
      print("Insufficient balance")
      return
    self.__balance -= amount
    print(f"Withdraw: {amount}")

  def show_balance(self):
    print(f"Balance: {self.__balance}")

account = Bank()
account.deposit(1000)
account.withdraw(600)
account.show_balance()

15
5
50
2.0

=============
Name: Muhammad Tayyab, Age: 18, Course: Artificial Intelligence

=============
Deposit: 1000
Withdraw: 600
Balance: 400

**Week#3**

NumPy

NumPy arrays are:
- faster
- memory efficient
- optimized for math

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

# // type
print(type(arr))
print(arr*2)

arr1 = np.zeros(5)
print(arr1)

arr2 = np.ones(5)
print(arr2)

arr3 = np.arange(5)
print(arr3)

arr4 = np.arange(0, 20, 2)  # even
print(arr4)

arr5 = np.arange(0, 20, 3)  # 0-20 wth 3 distance
print(arr5)

# multidimentional array
print("\n------ MULTIDIMENTIONAL ARRAY ------")
arr6 = np.array([
    [1,2,3],
    [6,7,8]
])
print(arr6)


# // indexing
print("\n------ INDEXING ------")
arr7 = np.array([2,4,5,6])
print(arr7[0])

print(arr6[0, 1])
print(arr6[1, 1])


# // slicing
print(arr7[1:4])


# STRIDES
print("\n------ STRIDES ------")
arr8 = np.array([1,2,4,2,6,8,9,1])
print(arr8[::2])  # Meaning: (start to end) (step size = 2)
print(arr8[::3])  # Meaning: (start to end) (step size = 3)



# RANDOM NUMBERS
print("\n------ RANDOM NUMBERS ------")
arr9 = np.random.randint(1,10,5)  # Meaning: (between 1 and 10) (generate 5 numbers)
print(arr9)


# SEEDS
print("\n------ SEEDS ------")
np.random.seed(42)  # Every time SAME output.

arr10 = np.random.randint(1, 100, 5)
print(arr10)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[ 2  4  6  8 10]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 1 2 3 4]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  3  6  9 12 15 18]

------ MULTIDIMENTIONAL ARRAY ------
[[1 2 3]
 [6 7 8]]

------ INDEXING ------
2
2
7
[4 5 6]

------ STRIDES ------
[1 4 6 9]
[1 2 9]

------ RANDOM NUMBERS ------
[5 7 3 7 8]

------ SEEDS ------
[52 93 15 72 61]

In [ ]:
# Numpy Assignment
import numpy as np

students_marks = np.array([50, 60, 70, 80, 90])
print(students_marks)

print(f"SUM: {np.sum(students_marks)}")
print(f"MAX: {np.max(students_marks)}")
print(f"MIN: {np.min(students_marks)}")
print(f"MEAN: {np.mean(students_marks)}")

[50 60 70 80 90]
SUM: 350
MAX: 90
MIN: 50
MEAN: 70.0

**Pandas**

In [ ]:
import pandas as pd

# === Series (module1) (1d)
print("\n------ SERIES ------")
series = pd.Series([10,20,30,40,50], index=["a", "b", "c", "d", "e"])
print(series);

# = functions
print("Values: ", series.values)
print("Index: ", series.index)
print("Index 'a': ", series["a"])
print("Datatype: ", series.dtype)
print("Values Count: ", series.value_counts())

print("Head: ", series.head())  # first 5
print("tail: ",series.tail())  # last 5

# === Dataframe (module2) (2d)
print("\n------ DATAFRAME ------")
data1 = {
    "Name": ["Ali", "Arsalan", "Aftab", "Ameen"],
    "Age": [20, 21, 19, 24],
    "City": ["Karachi", "Lahore", "Islamabad", "Karachi"]
}

df = pd.DataFrame(data1)
print(df)

# = load csv
print("\n------ Load CSV ------")

df1 = pd.read_csv("retail_sales.csv")
print("\n Info: \n", df1.info())

print("\n Shape: \n", df1.shape)
print("\n Datatype: \n", df1.dtypes)
print("\n Statics Summary: \n", df1.describe())


# = Indexing & Selection - loc & iloc
print("\n------ Indexing & Selection - loc & iloc ------")
print("\n Original DataFrame: \n", df)

subset_data1 = df.loc[0:2, ["Name", "City"]]
print("\n Subset DataFrame1 loc: \n", subset_data1)

subset_data2 = df.iloc[0:2, 0:3]
print("\n Subset DataFrame2 iloc: \n", subset_data2)

# Boolean filter
print("\n------ Boolean Filter ------")
high_age = df[df["Age"] > 20]
print("\n High age: \n", high_age)
print("\n Filtered Age Names: \n", high_age.loc[0:, ["Name"]])

# Import & Export - CSV, Excel & JSON
print("\n ----- Import & Export - CSV, Excel & JSON -----")
df2 = pd.read_csv(
    "retail_sales.csv",
    parse_dates=["Date"],
    dtype={
        "Category": "category",
        "Region": "category"
    })

print("\n Data Info: \n", df2.info())

clean_df2 = df2[df2["Sales"] > 0]
subset_df2 = clean_df2[["Date", "Category", "Sales", "Region"]]
print("\n Subset df2: \n", subset_df2)

------ SERIES ------
a    10
b    20
c    30
d    40
e    50
dtype: int64
Values:  [10 20 30 40 50]
Index:  Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
Index 'a':  10
Datatype:  int64
Values Count:  10    1
20    1
30    1
40    1
50    1
Name: count, dtype: int64
Head:  a    10
b    20
c    30
d    40
e    50
dtype: int64
tail:  a    10
b    20
c    30
d    40
e    50
dtype: int64

------ DATAFRAME ------
      Name  Age       City
0      Ali   20    Karachi
1  Arsalan   21     Lahore
2    Aftab   19  Islamabad
3    Ameen   24    Karachi

------ Load CSV ------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   object
 1   Category  1821 non-null   object
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   object
dtypes: float64(3), object(3)
memory usage: 85.7+ KB

 Info:
 None

 Shape:
 (1825, 6)

 Datatype:
 Date         object
Category     object
Sales       float64
Quantity    float64
Profit      float64
Region       object
dtype: object

 Statics Summary:
              Sales     Quantity       Profit
count  1823.000000  1820.000000  1825.000000
mean    980.482677    10.053846   248.696130
std     336.756618     5.515370   118.159627
min       0.000000     0.000000     0.000000
25%     784.071354     5.000000   156.916498
50%     997.725134    10.000000   229.344557
75%    1208.512721    15.000000   324.867847
max    1888.932537    19.000000   703.228418

------ Indexing & Selection - loc & iloc ------

 Original DataFrame:
       Name  Age       City
0      Ali   20    Karachi
1  Arsalan   21     Lahore
2    Aftab   19  Islamabad
3    Ameen   24    Karachi

 Subset DataFrame1 loc:
       Name       City
0      Ali    Karachi
1  Arsalan     Lahore
2    Aftab  Islamabad

 Subset DataFrame2 iloc:
       Name  Age     City
0      Ali   20  Karachi
1  Arsalan   21   Lahore

------ Boolean Filter ------

 High age:
       Name  Age     City
1  Arsalan   21   Lahore
3    Ameen   24  Karachi

 Filtered Age Names:
       Name
1  Arsalan
3    Ameen

 ----- Import & Export - CSV, Excel & JSON -----
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1821 non-null   category
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   category
dtypes: category(2), datetime64[ns](1), float64(3)
memory usage: 61.3 KB

 Data Info:
 None

 Subset df2:
            Date     Category        Sales Region
0    2023-01-01  Electronics  1149.014246  North
1    2023-01-01     Clothing   958.520710   East
2    2023-01-01   Home Goods  1473.763845  South
3    2023-01-01       Sports  1230.230419   West
4    2023-01-01         NaN?   828.585950   East
...         ...          ...          ...    ...
1820 2023-12-31  Electronics  1132.749004   West
1821 2023-12-31     Clothing   679.261971  North
1822 2023-12-31   Home Goods  1193.733728  South
1823 2023-12-31       Sports  1076.118706  North
1824 2023-12-31        Books   703.973443   East

[1778 rows x 4 columns]

In [ ]:
import pandas as pd

df3 = pd.read_csv(
    "retail_sales.csv",
    parse_dates=["Date"],
    dtype={
        "Category": "category"
    }
)

df3.info()

df3["Profit"] = pd.to_numeric(df3["Profit"])
df3["Region"] = df3["Region"].astype("category")
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1821 non-null   category
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   object
dtypes: category(1), datetime64[ns](1), float64(3), object(1)
memory usage: 73.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1821 non-null   category
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   category
dtypes: category(2), datetime64[ns](1), float64(3)
memory usage: 61.3 KB

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    "retail_sales.csv",
    parse_dates=["Date"],
    dtype={
        "Category": "category",
        "Region": "category"
    }
)

df.head()

df.info()

# Handling Missing Data
print(df.isna().sum())  # every column null values sum


df["Quantity"] = pd.to_numeric(df["Quantity"])
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].mode()[0])

df["Sales"] = df["Sales"].fillna(df["Sales"].median())

df["Category"] = df["Category"].fillna(df["Category"].mode()[0])


print("\n ===== After fillna")
df.info()

# Handling Missing Data
print(df.isna().sum())  # every column null values sum


# drop region
df.dropna(subset=["Region"], inplace=True)

print("\n ===== After dropna")
df.info()
# Handling Missing Data
print(df.isna().sum())  # every column null values sum

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1821 non-null   category
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   category
dtypes: category(2), datetime64[ns](1), float64(3)
memory usage: 61.3 KB
Date        0
Category    4
Sales       2
Quantity    5
Profit      0
Region      5
dtype: int64

 ===== After fillna
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1825 non-null   category
 2   Sales     1825 non-null   float64
 3   Quantity  1825 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   category
dtypes: category(2), datetime64[ns](1), float64(3)
memory usage: 61.3 KB
Date        0
Category    0
Sales       0
Quantity    0
Profit      0
Region      5
dtype: int64

 ===== After dropna
<class 'pandas.core.frame.DataFrame'>
Index: 1820 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1820 non-null   datetime64[ns]
 1   Category  1820 non-null   category
 2   Sales     1820 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1820 non-null   float64
 5   Region    1820 non-null   category
dtypes: category(2), datetime64[ns](1), float64(3)
memory usage: 75.2 KB
Date        0
Category    0
Sales       0
Quantity    0
Profit      0
Region      0
dtype: int64

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Category": ["Electric ", "HOME-APPLicance", " electronic", "FURNITURE", "furniture"]
})

# String & Text Cleaning
# strip
df["Category_Clean"] = df["Category"].str.strip().str.lower()

df["Category_Clean"] = df["Category_Clean"].str.replace("-", " ")
print(df)

          Category   Category_Clean
0        Electric          electric
1  HOME-APPLicance  home applicance
2       electronic       electronic
3        FURNITURE        furniture
4        furniture        furniture

In [ ]:
# Sorting & Ranking Data
import pandas as pd

df = pd.read_csv(
    "retail_sales.csv",
    parse_dates=["Date"],
    dtype={
        "Category": "category",
        "Region": "category"
    }
)

print("\n ===== head")
df.head()

# sort
print("\n ===== sorted head")
df_sorted = df.sort_values(by=["Quantity", "Sales"], ascending=[False, True])
df_sorted.head()

# group
print("\n ===== group head")
df["Sales_Rank"] = df.groupby("Quantity")["Sales"].rank(method="dense", ascending=False)
df

 ===== head

 ===== sorted head

 ===== group head

,Date,Category,Sales,Quantity,Profit,Region,Sales_Rank
0,2023-01-01,Electronics,1149.014246,11.0,383.664245,North,29.0
1,2023-01-01,Clothing,958.520710,7.0,224.054049,East,56.0
2,2023-01-01,Home Goods,1473.763845,2.0,466.593090,South,7.0
3,2023-01-01,Sports,1230.230419,6.0,123.310460,West,24.0
4,2023-01-01,NaN?,828.585950,12.0,88.591355,East,68.0
...,...,...,...,...,...,...,...
1820,2023-12-31,Electronics,1132.749004,14.0,353.464221,West,30.0
1821,2023-12-31,Clothing,679.261971,8.0,183.860200,North,88.0
1822,2023-12-31,Home Goods,1193.733728,10.0,359.010938,South,32.0
1823,2023-12-31,Sports,1076.118706,17.0,259.570916,North,38.0
1824,2023-12-31,Books,703.973443,14.0,134.106006,East,73.0

In [ ]:
# Merging & Joining DataFrames
# joins (LEFT, INNER, RIGHT, OUTER)

import pandas as pd

customer = pd.DataFrame({
    "CustomerID": [1,2,3],
    "Name": ["ALI", "AFTAB", "AHMED"]
})

orders = pd.DataFrame({
    "OrderID": [101,102,103,104],
    "CustomerID": [1,2,3,2],
    "Amount": [250,150,450,300]
})

df_inner = pd.merge(customer, orders, on="CustomerID", how="inner")
print("\nInner Merge: \n", df_inner)

df_left = pd.merge(customer, orders, on="CustomerID", how="left")
print("\nLeft Merge: \n", df_left)

df_right = pd.merge(customer, orders, on="CustomerID", how="right")
print("\nRight Merge: \n", df_right)

df_outer = pd.merge(customer, orders, on="CustomerID", how="outer")
print("\nOuter Merge: \n", df_outer)


df_concat = pd.concat([customer, customer])
print("\nConcat: \n", df_concat)

Inner Merge:
    CustomerID   Name  OrderID  Amount
0           1    ALI      101     250
1           2  AFTAB      102     150
2           2  AFTAB      104     300
3           3  AHMED      103     450

Left Merge:
    CustomerID   Name  OrderID  Amount
0           1    ALI      101     250
1           2  AFTAB      102     150
2           2  AFTAB      104     300
3           3  AHMED      103     450

Right Merge:
    CustomerID   Name  OrderID  Amount
0           1    ALI      101     250
1           2  AFTAB      102     150
2           3  AHMED      103     450
3           2  AFTAB      104     300

Outer Merge:
    CustomerID   Name  OrderID  Amount
0           1    ALI      101     250
1           2  AFTAB      102     150
2           2  AFTAB      104     300
3           3  AHMED      103     450

Concat:
    CustomerID   Name
0           1    ALI
1           2  AFTAB
2           3  AHMED
0           1    ALI
1           2  AFTAB
2           3  AHMED

In [ ]:
# Applying Functions - apply, map & pipe
import pandas as pd

df = pd.read_csv(
    "ecommerce_sales_analytics_5000.csv",
    parse_dates=["order_date"]
)

df.info()
df.head()

# map
print("\n ==== MAP: \n")
df["payment_type"] = df["payment_method"].map({
    "Card": "Digital",
    "Wallet": "Digital",
    "COD": "Cash"
})

df["payment_type"].unique()
df.head()

print("\n ==== total payments: \n")
df.groupby("payment_type").size()


# Apply
print("\n ==== Apply: \n")
def revenue_category(row):
  if row["revenue"] > 500:
    return "High"
  elif row["revenue"] >= 200:
    return "Medium"
  else:
    return "Low"

df["revenue_category"] = df.apply(revenue_category, axis=1)
df["revenue_category"].value_counts()


# Sample
print("\n ==== Sample: \n")
df[["revenue", "revenue_category"]].sample(10)

# === PIPE ===
def add_profit(data):
  data["profit"] = data["revenue"] * 0.20
  return data

def add_net_revenue(data):
  data["net_revenue"] = data["revenue"] - data["profit"]
  return data

df = (
    df
    .pipe(add_profit)
    .pipe(add_net_revenue)
)

print("\n ==== Pipe: \n")
df[["revenue", "profit", "net_revenue"]].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   datetime64[ns]
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   object
 4   region            5000 non-null   object
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   object
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(4), object(3)
memory usage: 468.9+ KB

 ==== MAP:


 ==== total payments:


 ==== Apply:


 ==== Sample:


 ==== Pipe:

   revenue   profit  net_revenue
0  1883.20  376.640     1506.560
1   304.10   60.820      243.280
2   644.35  128.870      515.480
3  2569.90  513.980     2055.920
4   468.56   93.712      374.848

In [ ]:
# EDA
import pandas as pd